# Generated by Django 5.2.7 on 2025-10-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
